### PR TITLE
Add toggle to always show input slider

### PR DESCRIPTION
**Pull request by emiliopedrollo**

### CODE REVIEW

**Comment by emiliopedrollo** [comment]
Turns out it was incompatible with `Quick Settings Audio Panel` as the toggle on that extension to always show input slider is somewhere in this extension. 

In my previous tests I was always disabling and re-enabling QSAP which would make the slider visible. But it would always disappear after restart.

Recreating the option here seems to be the only way to make it truly always visible.

**Comment by marcinjahn** [comment]
Why is it needed as part of this extension? There already are a few other extensions that enable that feature

**Comment by marcinjahn** [comment]
> Turns out it was incompatible with `Quick Settings Audio Panel` as the toggle on that extension to always show input slider is somewhere in this extension.
> 
> In my previous tests I was always disabling and re-enabling QSAP which would make the slider visible. But it would always disappear after restart.
> 
> Recreating the option here seems to be the only way to make it truly always visible.

I think that Quick Settings Tweaker implements it in a less invasive way, and does the same thing

**Comment by emiliopedrollo** [comment]
Yeah. It is actually compatible with Quick Settings Tweaker but not with Quick Settings Audio Panel, with is the first result for Quick Settings Audio Panel which is the first result on Extensions Manager for "Quick Settings" or even "Audio":

image
image


There may be other extensions with that would have this option broken when using in combination with Quick Settings Audio Devices Hider.

**Comment by marcinjahn** [comment]
What do you think about fixing the wrong behavior in the Quick Settings Audio Panel extensions itself?
I must say I'm not fond of replicating functionalities that other extensions already have. I'd rather prefer to redirect people to use these extensions instead.
Regarding this issue, I think a good approach would be to:

1. Add a note in README and manifest about potential issues with Quick Settings Audio Panel, with a recommendation of trying out Quick Settings Tweaker instead - I can do that
2. Fix the issue in Quick Settings Audio Panel.

**Pull request closed without merging**
